### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by GorkyTS** [Laevitas/laevitas-feature-issue-tracker#10]
Dashboard: Bug - options calculator only allows to one leg expiry dates, unable to choose different expiry dates between legs

**Comment by hedikarray1** [comment]
Hello @GorkyTS,
It sounds like you're having a question about the options calculator and the ability to choose different expiry dates between legs. Actually, there's a way to achieve this.
If the strategy you're using currently doesn't provide the option to choose different expiry dates between legs, you can consider using the 'Custom Strategy' or 'Calendar Spread' strategy. These strategies are designed to allow you to select different expiry dates for the legs of your options trade. The 'Custom Strategy' option typically lets you create more complex combinations of options with varying expiry dates, while the 'Calendar Spread' strategy specifically involves choosing different expiration dates to take advantage of time decay.
By utilizing these strategies, you'll have the flexibility to construct options trades that involve different expiry dates between legs, which can be particularly useful for various trading scenarios.
Feel free to explore these strategies, and don't hesitate to reach out if you have any further questions or need assistance in implementing these approaches.
Happy trading!

**Comment by GorkyTS** [comment]
Hello Hedi,

Thanks for your email. Actually the bottleneck was when you click the
strategies section (options) and see the ''custom strategies'' - those
shall be executed strategies by different trades, and if there are
different expiry dates, the calculator does not allow to calculate results,
seems like this issue has been resolved already.

I hereby want to ask something different, once you click the ''calculate
hedge'' during the backtest actions, after getting the results, what are
the spot and future numbers stand for? Please explain this to me. One more
question. Do you think that ''Zero Solver'' can be used for hedging
existing positions?

Thanks for your understanding and help

hedi karray ***@***.***>, 16 Ağu 2023 Çar, 14:23 tarihinde
şunu yazdı:
