### ISSUE TITLE
Extreme Funding Not in Catalog

### ISSUE THREAD

**Issue by joemccann** [Laevitas/laevitas-feature-issue-tracker#11]
Go here:

https://api.laevitas.ch/api/catalog/v2

And search for the Extreme Funding method.

It doesn't exist but is on your API docs page.

**Comment by joemccann** [comment]
I'd highly recommend getting the catalog() and your API docs in sync. This should be done programmatically.

**Comment by Laevitaas** [comment]
hi @joemccann, is there an endpoint in particular which you are looking for? I'm not sure we have one called Extreme Funding.

For the automated catalog API docs, we are working on this and hoping to have it ready soon @MoetezL

**Comment by joemccann** [comment]
It's literally on your docs page:

<img width="846" alt="CleanShot 2023-08-24 at 04 41 15" src="https://github.com/Laevitas/laevitas-feature-issue-tracker/assets/48234/a673cbdc-88c1-498e-82bc-ef488406bc62">

https://docs.laevitas.ch/futures/derivs#extreme-funding

**Comment by Laevitaas** [comment]
Just realised that this endpoint got delisted for some reason, we'll it bring back asap. @MoetezL is on holidays but he's back next week, we'll fix this and ensure the catalog is updated programmatically as well. Thanks for the feedback

**Comment by MoetezL** [comment]
hello @joemccann .
I sincerely apologize for the oversight and the delay in addressing this. i'll be working on fixing the missing endpoint promptly. additionally, i'm looking into automating the process to ensure that the API and its documentation remain consistent in the future. 
thank you for bringing this to our attention, and I appreciate your patience and understanding

**Comment by MoetezL** [comment]
Hi @joemccann ,

I apologize for the delay. Here's the endpoint of the extreme funding: https://api.laevitas.ch/analytics/derivs/top_funding/{market} . 
Additionally, the GitBook sync should be completed by the end of this week.

Thank you for your patience and understanding.
