### ISSUE TITLE
Bug: staging.laevitas.ch/assets/options/activity/BTC/[exchange] Expiry fields are empty

### ISSUE THREAD

**Issue by Utone** [Laevitas/laevitas-feature-issue-tracker#16]
Staging bug.
Assets/
options/
activity/
asset/
Exchanges

<img width="1013" alt="Screenshot 2024-02-09 at 21 40 29" src="https://github.com/Laevitas/laevitas-feature-issue-tracker/assets/5865016/bce8e3da-4464-419c-8d15-5161548270e9">
On staging.laevitas.ch/assets/options/activity/BTC/[exchange] Expiry fields are empty

Every exchange.
Production: is unaffected, works as it should.

**Comment by Laevitaas** [comment]
@Utone thanks for pinging its now fixed
