### ISSUE TITLE
Endpoint to pull 'Alts Derivs' options

### ISSUE THREAD

**Issue by sudheerg127** [Laevitas/laevitas-feature-issue-tracker#7]
There seems to be no endpoint to pull 'Alts Derivs' options through the API. Can you please add it so it can be pulled using the API?

**Comment by MoetezL** [comment]
Thank you for reaching out and expressing your interest in the Alts Derivs options. We appreciate your feedback and are always looking for ways to enhance our API.
We have taken note of your request to add an endpoint for pulling Alts Derivs options through the API

**Comment by MoetezL** [comment]
Hello @sudheerg127 ,

We've added the requested endpoint to our API. You can check it out on our Swagger documentation here: https://api.laevitas.ch/swagger/#/Analytics%20Derivs/getAltOptionDataByMarket

Let us know if you have any further questions or feedback. Thank you for your input!
